unique_ids:
  assets:
    standard-page.html: MT2FCFQSRC6XGH5EVLDJTTKQT2KTDAOT
    theme.css: SAMCMRPD7LPAQ2EQNED43VBNEHM7B5HR
  forms:
    Form1: FV7QAKI5ZZUAIJPFWSPGMP5TVUNIZSM5
  modules: {}
  scripts: {}
  server_modules: {}
